### PR TITLE
Updated ClickableTextureComponent parameters

### PR DESCRIPTION
**Pull request by IngeniousGamer**
Parameters now match Latest API for v1.1

### CODE REVIEW

**Comment by spacechase0** [comment]
NewLoadMenu is a copy/paste of vanilla LoadGameMenu, and this doesn't quite match up with that.

For instance, up arrow is:
`this.upArrow = new ClickableTextureComponent(new Rectangle(this.xPositionOnScreen + this.width + Game1.tileSize / 4, this.yPositionOnScreen + Game1.tileSize / 4, 11 * Game1.pixelZoom, 12 * Game1.pixelZoom), Game1.mouseCursors, new Rectangle(421, 459, 11, 12), (float)Game1.pixelZoom, false);`
But the ok button is:
`this.okDeleteButton = new ClickableTextureComponent("OK", new Rectangle((int)Utility.getTopLeftPositionForCenteringOnScreen(Game1.tileSize, Game1.tileSize, 0, 0).X - Game1.tileSize, (int)Utility.getTopLeftPositionForCenteringOnScreen(Game1.tileSize, Game1.tileSize, 0, 0).Y + Game1.tileSize * 2, Game1.tileSize, Game1.tileSize), null, null, Game1.mouseCursors, Game1.getSourceRectForStandardTileSheet(Game1.mouseCursors, 46, -1, -1), 1f, false);`

I don't know if this would break anything, so I'm just using the copy/paste for now.

**Comment by phoenx34** [comment]
In the latest API for v1.1 there is a new parameter for ClickableTextureComponent. Its a string called name, so IngeniousGamer just added blank "", thus fixing syntax errors thrown when trying to use it with SDV1.1 I made the changes as well, gonna pack the files and try running the mod now and see if these are the only changes required for functionality with the new API and SDV1.1

**Comment by phoenx34** [comment]
Update, everything including the new gui works so far on 1.1... I don't know how its gonna handle the different map styles but I can keep testing it and I will post logs if I run in to any errors.

**Comment by spacechase0** [comment]
Yeah, I understand what he did. I wrote this monstrosity you know. :P

The reason I'm not just putting out a new version with that fixed is because there's a bit more to it than that. At the very least, NewSaveGame needs to be updated. However when I decompile the original SaveGame (tried with both ILSpy and dotPeek), `getLoadEnumerator` and `getSaveEnumerator` are just compiler-generated stubs. The decompiler can't handle them properly for some reason. They show the bytecode, but there's no way I'm translating 250+ lines of C# from bytecode by hand. :P

So for instance, I'm fairly certain your farm type and whether mobs spawn on your farm or not won't save properly. Well, at all. So whenever you save the game, it'll revert to the default farm type (and probably no mob spawns, even if you turned it on at the dark altar) when you start the game again. Also, since this code is used for sending the world to the clients, the clients will never receive the proper farm type.

There's other stuff too, which is why I wanted to test the new features. I'm fairly certain junimo huts and casks will cause issues. Who knows what farmhouse basements will do, etc.

**Comment by phoenx34** [comment]
ah. I was just about to try that... you think Eric made Chucklefish intentionally do this because they are on to us lol? and yeah, the maps do reset sadly.

**Comment by phoenx34** [comment]
It worked, I have the c#. Had to zip it to attach it. 
[save_load_enums.zip](https://github.com/spacechase0/StardewValleyMP/files/509955/save_load_enums.zip)

**Comment by spacechase0** [comment]
Pretty sure it was accidental. I think my version does that in ILSpy as well. :P

That's awesome, thank you so much. Hopefully I'll have the spare time tomorrow to get the mod fully working.

**Comment by phoenx34** [comment]
Cool :+1:  and no problem! I am super busy tomorrow so I probably won't be able to do much work on this but I will definitely work on the errors on thursday or late tomorrow night.

**Pull request closed without merging**
